// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Test1._1.Models.Entity;

#nullable disable

namespace Test1._1.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20250228162247_add-test")]
    partial class addtest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Test1._1.Models.Entity.ApplicantAdvertisment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicantId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("JobAdvertismentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Submation_Date")
                        .HasColumnType("DATETIME");

                    b.Property<string>("TellAboutYou")
                        .IsRequired()
                        .HasColumnType("Varchar");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId");

                    b.HasIndex("JobAdvertismentId");

                    b.ToTable("ApplicantAdvertisments", (string)null);
                });

            modelBuilder.Entity("Test1._1.Models.Entity.ApplicantTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppPaymentId")
                        .HasColumnType("int");

                    b.Property<int>("AppSubscrabtionId")
                        .HasColumnType("int");

                    b.Property<int>("ApplicantId")
                        .HasColumnType("int");

                    b.Property<int>("ApplicantPaymentId")
                        .HasColumnType("int");

                    b.Property<int>("ApplicantSubscrabtionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId");

                    b.HasIndex("ApplicantPaymentId");

                    b.HasIndex("ApplicantSubscrabtionId");

                    b.ToTable("ApplicantTransactions");
                });

            modelBuilder.Entity("Test1._1.Models.Entity.CompanyTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyPaymentId")
                        .HasColumnType("int");

                    b.Property<int>("CompanySubId")
                        .HasColumnType("int");

                    b.Property<int>("CompanySubscraptionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CompanyPaymentId");

                    b.HasIndex("CompanySubscraptionId");

                    b.ToTable("CompanyTransactions");
                });

            modelBuilder.Entity("Test1._1.Models.Entity.JobAdvertisment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Certificate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("Job_time")
                        .HasColumnType("time");

                    b.Property<string>("Jobdetail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumEmployee")
                        .HasColumnType("int");

                    b.Property<string>("governorate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("jobtitle")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("salary")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("JobAdvertisments", (string)null);
                });

            modelBuilder.Entity("Test1._1.Models.Entity.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Payments");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Test1._1.Models.Entity.Subscraption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NumAllowed")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SubType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Subscraptions");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Test1._1.Models.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Fname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("VARCHAR");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Lname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Test1._1.Models.Entity.ApplicantPayment", b =>
                {
                    b.HasBaseType("Test1._1.Models.Entity.Payment");

                    b.ToTable("ApplicantPayments");
                });

            modelBuilder.Entity("Test1._1.Models.Entity.CompanyPayment", b =>
                {
                    b.HasBaseType("Test1._1.Models.Entity.Payment");

                    b.ToTable("CompanyPayments");
                });

            modelBuilder.Entity("Test1._1.Models.Entity.ApplicantSubscrabtion", b =>
                {
                    b.HasBaseType("Test1._1.Models.Entity.Subscraption");

                    b.ToTable("ApplicantSubscrabtions");
                });

            modelBuilder.Entity("Test1._1.Models.Entity.CompanySubscrabtion", b =>
                {
                    b.HasBaseType("Test1._1.Models.Entity.Subscraption");

                    b.ToTable("CompanySubscraptions");
                });

            modelBuilder.Entity("Test1._1.Models.Entity.Admin", b =>
                {
                    b.HasBaseType("Test1._1.Models.Entity.User");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Test1._1.Models.Entity.Applicant", b =>
                {
                    b.HasBaseType("Test1._1.Models.Entity.User");

                    b.Property<string>("CV")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<string>("Field_work")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR");

                    b.Property<int>("Years_experience")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.ToTable("Applicants");
                });

            modelBuilder.Entity("Test1._1.Models.Entity.Company", b =>
                {
                    b.HasBaseType("Test1._1.Models.Entity.User");

                    b.Property<string>("CommercialRegister")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("VARCHAR");

                    b.Property<int>("CurrentNumEmployees")
                        .HasColumnType("int");

                    b.Property<string>("FiledWork")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("TaxCard")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("VARCHAR");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Test1._1.Models.Entity.ApplicantAdvertisment", b =>
                {
                    b.HasOne("Test1._1.Models.Entity.Applicant", "Applicant")
                        .WithMany("ApplicantAdvertisments")
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Test1._1.Models.Entity.JobAdvertisment", "JobAdvertisment")
                        .WithMany("ApplicantAdvertisments")
                        .HasForeignKey("JobAdvertismentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Applicant");

                    b.Navigation("JobAdvertisment");
                });

            modelBuilder.Entity("Test1._1.Models.Entity.ApplicantTransaction", b =>
                {
                    b.HasOne("Test1._1.Models.Entity.Applicant", "Applicant")
                        .WithMany("ApplicantTranactions")
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Test1._1.Models.Entity.ApplicantPayment", "ApplicantPayment")
                        .WithMany("ApplicantTransactions")
                        .HasForeignKey("ApplicantPaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Test1._1.Models.Entity.ApplicantSubscrabtion", "ApplicantSubscrabtion")
                        .WithMany("ApplicantTrasactions")
                        .HasForeignKey("ApplicantSubscrabtionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Applicant");

                    b.Navigation("ApplicantPayment");

                    b.Navigation("ApplicantSubscrabtion");
                });

            modelBuilder.Entity("Test1._1.Models.Entity.CompanyTransaction", b =>
                {
                    b.HasOne("Test1._1.Models.Entity.Company", "Company")
                        .WithMany("CompanyTransactions")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Test1._1.Models.Entity.CompanyPayment", "CompanyPayment")
                        .WithMany("CompanyTransactions")
                        .HasForeignKey("CompanyPaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Test1._1.Models.Entity.CompanySubscrabtion", "CompanySubscraption")
                        .WithMany("CompanyTransactions")
                        .HasForeignKey("CompanySubscraptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("CompanyPayment");

                    b.Navigation("CompanySubscraption");
                });

            modelBuilder.Entity("Test1._1.Models.Entity.JobAdvertisment", b =>
                {
                    b.HasOne("Test1._1.Models.Entity.Company", "Company")
                        .WithMany("JobAdvertisments")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Test1._1.Models.Entity.ApplicantPayment", b =>
                {
                    b.HasOne("Test1._1.Models.Entity.Payment", null)
                        .WithOne()
                        .HasForeignKey("Test1._1.Models.Entity.ApplicantPayment", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Test1._1.Models.Entity.CompanyPayment", b =>
                {
                    b.HasOne("Test1._1.Models.Entity.Payment", null)
                        .WithOne()
                        .HasForeignKey("Test1._1.Models.Entity.CompanyPayment", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Test1._1.Models.Entity.ApplicantSubscrabtion", b =>
                {
                    b.HasOne("Test1._1.Models.Entity.Subscraption", null)
                        .WithOne()
                        .HasForeignKey("Test1._1.Models.Entity.ApplicantSubscrabtion", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Test1._1.Models.Entity.CompanySubscrabtion", b =>
                {
                    b.HasOne("Test1._1.Models.Entity.Subscraption", null)
                        .WithOne()
                        .HasForeignKey("Test1._1.Models.Entity.CompanySubscrabtion", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Test1._1.Models.Entity.Admin", b =>
                {
                    b.HasOne("Test1._1.Models.Entity.User", null)
                        .WithOne()
                        .HasForeignKey("Test1._1.Models.Entity.Admin", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Test1._1.Models.Entity.Applicant", b =>
                {
                    b.HasOne("Test1._1.Models.Entity.User", null)
                        .WithOne()
                        .HasForeignKey("Test1._1.Models.Entity.Applicant", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Test1._1.Models.Entity.Company", b =>
                {
                    b.HasOne("Test1._1.Models.Entity.User", null)
                        .WithOne()
                        .HasForeignKey("Test1._1.Models.Entity.Company", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Test1._1.Models.Entity.JobAdvertisment", b =>
                {
                    b.Navigation("ApplicantAdvertisments");
                });

            modelBuilder.Entity("Test1._1.Models.Entity.ApplicantPayment", b =>
                {
                    b.Navigation("ApplicantTransactions");
                });

            modelBuilder.Entity("Test1._1.Models.Entity.CompanyPayment", b =>
                {
                    b.Navigation("CompanyTransactions");
                });

            modelBuilder.Entity("Test1._1.Models.Entity.ApplicantSubscrabtion", b =>
                {
                    b.Navigation("ApplicantTrasactions");
                });

            modelBuilder.Entity("Test1._1.Models.Entity.CompanySubscrabtion", b =>
                {
                    b.Navigation("CompanyTransactions");
                });

            modelBuilder.Entity("Test1._1.Models.Entity.Applicant", b =>
                {
                    b.Navigation("ApplicantAdvertisments");

                    b.Navigation("ApplicantTranactions");
                });

            modelBuilder.Entity("Test1._1.Models.Entity.Company", b =>
                {
                    b.Navigation("CompanyTransactions");

                    b.Navigation("JobAdvertisments");
                });
#pragma warning restore 612, 618
        }
    }
}
